### ISSUE TITLE
Sphinx warnings with sphix 1.3.5

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf#192] opened 2016-02-29 21:36 UTC
The sphinx build in master currently fails with this kind of warnings:

```
WARNING: Could not parse literal_block as "yaml". highlighting skipped.
```

These are issued from code like

```
.. runcode::

   from asdf import AsdfFile

   # Make the tree structure, and create a AsdfFile from it.
   tree = {'hello': 'world'}
   ff = AsdfFile(tree)
   ff.write_to("test.asdf")

   # You can also make the AsdfFile first, and modify its tree directly:
   ff = AsdfFile()
   ff.tree['hello'] = 'world'
   ff.write_to("test.asdf")

.. asdf:: test.asdf
```

This is discussed a bit in #190 in [this comment](https://github.com/spacetelescope/pyasdf/pull/190#issuecomment-188350741).

**Comment by bsipocz** [comment] 2016-04-13 23:18
I think has something to do with the ``asdf`` directive, however it's a bit complicated so I didn't find a quick solution.

In the meantime I've fixed the sphinx version to <1.3.5 in #194 so they won't show up in every PR.

**Comment by nden** [comment] 2016-04-14 02:03
Yes, it's in the definition of the `AsdfDirective` class but I haven't had time to look into it.
It's a warning that `Pygments` could not do correct language highlighting so it's not critical although it would be nice to fix it.

**Comment by embray** [comment] 2016-04-14 08:15
The problem appears to be [here](https://github.com/spacetelescope/asdf/blob/18ec694646f37ab7d04c9c4306eb9bb0bee79165/docs/sphinxext/example.py#L84).  The problem is that the `AsdfDirective` is creating a single `literal_block` node containing the ASDF header followed by the YAML tree.  The whole block is marked as having the language "yaml", but the ASDF header is not valid YAML (well, arguably it's a comment in YAML, but my guess--and I haven't confirmed this--is that the syntax highlighter doesn't support comments coming before the `%YAML` directive).

Technically, according to the [low-level layout of the ASDF format](http://asdf-standard.readthedocs.org/en/latest/file_layout.html#low-level-file-layout) the header is a separate section of the file from the YAML tree anyways.  So I think a fix to this would be to change the `AsdfDirective` slightly to output the header in a separate literal node from the tree (just as it outputs the block headers as a separate node currently).

**Comment by embray** [comment] 2016-04-14 08:36
Nevermind--that doesn't appear to be exactly the issue after all.  I tested it and the yaml highligher from pygments had no problem with this, at least not directly (still might make sense to put the header in a separate node though).

**Comment by embray** [comment] 2016-04-14 09:00
Okay, I think I see where the problem probably is. I think it's a bug in the pygments lexer.  It's barfing on lines like this one:

```
asdf_library: !core/software-1.0.0 {author: Space Telescope Science Institute, homepage: 'http://github.com/spacetelescope/asdf',
  name: asdf, version: 1.1.0.dev722}
```

If I remove the `!core/software-1.0.0` tag it works.  So it seems that it can't handle an inline map element split across multiple lines if it is preceded by a tag.

**Comment by embray** [comment] 2016-04-14 10:12
Here we go:
https://bitbucket.org/birkenfeld/pygments-main/pull-requests/584/fix-incorrect-lexing-of-yaml-tags/diff

In principle we can work around this now by monkey-patching.  The `AsdfDirective` (or the module containing it) can import the `YamlLexer` from `pygments` and update `YamlLexer.tokens['descriptors']` to use my updated regexp.

**Comment by embray** [comment] 2016-05-06 09:15
My fix to the pygments lexer has been merged.

**Closed** 2017-08-29 20:49 UTC
