### ISSUE TITLE
Add a commandline utility

### ISSUE THREAD

**Issue by mdboom** [spacetelescope/asdf#12] opened 2014-04-09 23:31 UTC
For the basic operations -- implode/explode/garbage collect/validate.

**Comment by drdavella** [comment] 2017-08-03 17:01
This currently exists for all but validate.

**Comment by drdavella** [comment] 2017-08-03 18:24
@perrygreenfield and @nden, do we know what was intended by the `validate` command line tool? Files are automatically validated when they are opened. Is the point just to return whether or not a given file is well-formed ASDF or not?

**Comment by nden** [comment] 2017-08-03 19:00
My guess, given the date of the issue, is that the code has evolved and this is not needed any more.

**Comment by drdavella** [comment] 2017-08-03 19:09
Okay, that seems reasonable. It was also be very easy to provide a simple yes/no interface to indicate whether a file is valid or not. Although in the case that a file was not valid, you'd probably want to know why...

**Comment by drdavella** [comment] 2017-08-03 20:14
Closing since a command line utility already exists. If a validation feature is specifically requested, we can open a new issue.

**Closed by drdavella** 2017-08-03 20:14 UTC
Labels: enhancement
