### ISSUE TITLE
1.1.0 test_inverse_transforms FAILED

### ISSUE THREAD

**Issue by olebole** [spacetelescope/asdf#205] opened 2016-06-26 12:19 UTC
WIth astropy 1.2.1 (not sure if this is the cause or just a coincidence), the `test_inverse_transforms` test fails:

```
___________________________ test_inverse_transforms ____________________________

tmpdir = local('/tmp/pytest-of-root/pytest-0/test_inverse_transforms0')

    @pytest.mark.skipif('not HAS_ASTROPY')
    def test_inverse_transforms(tmpdir):
        rotation = astmodels.Rotation2D(32)
        rotation.inverse = astmodels.Rotation2D(45)

        real_rotation = astmodels.Rotation2D(32)

        tree = {
            'rotation': rotation,
            'real_rotation': real_rotation
            }

        def check(ff):
            assert ff.tree['rotation'].inverse.angle == 45

>       helpers.assert_roundtrip_tree(tree, tmpdir, check)

asdf/tags/transform/tests/test_transform.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
asdf/tests/helpers.py:120: in assert_roundtrip_tree
    asdf_check_func(ff)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

ff = <asdf.asdf.AsdfFile object at 0x7fd58d84bdd0>

    def check(ff):
>       assert ff.tree['rotation'].inverse.angle == 45
E       assert Parameter('angle', value=-32.0) == 45
E        +  where Parameter('angle', value=-32.0) = <Rotation2D(angle=-32.0)>.angle
E        +    where <Rotation2D(angle=-32.0)> = <Rotation2D(angle=32.0)>.inverse

asdf/tags/transform/tests/test_transform.py:57: AssertionError
```

This was observed in a test rebuild for reproducibility. Full log [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=828172;filename=python-asdf.1.1.0-2.unstable.amd64.log.txt.gz;msg=5). #Debian bug [here](https://bugs.debian.org/828172).

**Comment by nden** [comment] 2016-06-27 18:56
I believe this is caused by name changes to `inverse` in astropy 1.2 and has been resolved on master. Should have a new release soon.

**Comment by olebole** [comment] 2016-07-05 20:20
I can confirm this: applying 6ee20e8f6521852f1f904156dda341d5a8416f13 fixes the problem.

**Comment by nden** [comment] 2016-11-04 16:37
Finally there's a new release on pypi (1.2.0) which incorporates the fix for this problem.

**Closed by nden** 2016-11-04 16:37 UTC
