### ISSUE TITLE
Asdf fails to load json schema files

### ISSUE THREAD

**Issue by bernie-simon** [spacetelescope/asdf#314] opened 2017-08-24 19:48 UTC
Asdf loads schema files using generic_io.get_file. It forces the file to be opened in binary mode. This returns the contents of the file as a byte array under Python 3. The json parser chokes on the byte array, saying it wants the str type.

Adding this issue for tracking, although if someone else wants to take a swing at it, feel free.

**Comment by drdavella** [comment] 2017-08-24 19:56
@bernie-simon do you have a minimal example that reproduces this?

**Comment by drdavella** [comment] 2017-08-24 20:00
Also, this is a duplicate of #242.

**Comment by drdavella** [comment] 2017-08-25 13:27
This apparently only manifests itself on Python 3.5. Here is a minimal code snippet that should reproduce the error:
```python
from asdf import schema
schema.load_schema(json_filename)
```

Apparently this is not currently being tested, so a reproducer needs to be added to the test suite first.

**Closed** 2017-08-25 16:46 UTC
